name       : xorg-driver-video-nouveau
version    : 1.0.14
release    : 19
source     :
    - git|git://anongit.freedesktop.org/nouveau/xf86-video-nouveau : e472b47d15634a864c8c981ed588d882aceaf26b
license    :
    - MIT
summary    : Alternative video driver for NVIDIA graphics cards
component  : xorg.driver
builddeps  :
    - pkgconfig(xorg-server)
    - pkgconfig(libdrm)
    - pkgconfig(resourceproto)
    - pkgconfig(scrnsaverproto)
    - pkgconfig(dri3proto)
    - pkgconfig(xorg-macros)
optimize   : no-bind-now
libsplit   : no
description: |
    The Xorg Nouveau Driver package contains the X.Org Video Driver for NVidia Cards including RIVA TNT, RIVA TNT2, GeForce 256, QUADRO, GeForce2, QUADRO2, GeForce3, QUADRO DDC, nForce, nForce2, GeForce4, QUADRO4, GeForce FX, QUADRO FX, GeForce 6XXX and GeForce 7xxx chipsets.
setup      : |
    %autogen CFLAGS="$CFLAGS -O3"
build      : |
    %make
install    : |
    %make_install
