name       : xorg-driver-video-nouveau
version    : 1.0.16
release    : 28
source     :
    - https://xorg.freedesktop.org/archive/individual/driver/xf86-video-nouveau-1.0.16.tar.bz2 : 304060806415579cdb5c1f71f1c54d11cacb431b5552b170decbc883ed43bf06
license    :
    - MIT
summary    : Alternative video driver for NVIDIA graphics cards
component  : xorg.driver
builddeps  :
    - pkgconfig(xorg-server)
    - pkgconfig(libdrm)
    - pkgconfig(resourceproto)
    - pkgconfig(scrnsaverproto)
    - pkgconfig(dri3proto)
    - pkgconfig(xorg-macros)
optimize   :
    - no-bind-now
    - no-symbolic
libsplit   : no
replaces   :
    - nvidia-304-glx-driver
    - nvidia-304-glx-driver-common
    - nvidia-304-glx-driver-current
description: |
    The Xorg Nouveau Driver package contains the X.Org Video Driver for NVidia Cards including RIVA TNT, RIVA TNT2, GeForce 256, QUADRO, GeForce2, QUADRO2, GeForce3, QUADRO DDC, nForce, nForce2, GeForce4, QUADRO4, GeForce FX, QUADRO FX, GeForce 6XXX and GeForce 7xxx chipsets.
setup      : |
    %reconfigure CFLAGS="$CFLAGS -O3"
build      : |
    %make
install    : |
    %make_install
